Import("*")

SimObject("Sau.py", sim_objects=["SauModel"])

Source("address_generator.cc")
Source("a_register_file.cc")
Source("array_input_scheduler.cc")
Source("command.cc")
Source("memory_port.cc")
Source("result_scheduler.cc")
Source("sau_model.cc")
Source("token_pipeline.cc")
Source("trace_writer.cc")

DebugFlag("SAU")

GTest("address_generator.test", "address_generator.test.cc",
      "address_generator.cc", "command.cc")
GTest("a_register_file.test", "a_register_file.test.cc",
      "a_register_file.cc", "command.cc")
GTest("array_input_scheduler.test", "array_input_scheduler.test.cc",
      "array_input_scheduler.cc")
GTest("command.test", "command.test.cc", "command.cc")
GTest("memory_port.test", "memory_port.test.cc", "memory_port.cc",
      "../mem/packet.cc", "../mem/port.cc", "../mem/protocol/functional.cc",
      "../mem/protocol/timing.cc", "../sim/bufval.cc", "../sim/port.cc",
      with_tag("gem5 trace"))
GTest("token_pipeline.test", "token_pipeline.test.cc", "token_pipeline.cc")
GTest("trace_writer.test", "trace_writer.test.cc", "trace_writer.cc")
GTest("result_scheduler.test", "result_scheduler.test.cc",
      "result_scheduler.cc")
