Import("*")

SimObject("Sau.py", sim_objects=["SauModel"])

Source("address_generator.cc")
Source("address_program.cc")
Source("a_register_file.cc")
Source("boundary_trace.cc")
Source("array_input_scheduler.cc")
Source("command.cc")
Source("csr_config.cc")
Source("csr_fixture.cc")
Source("functional_memory.cc")
Source("input_datapath.cc")
Source("memory_port.cc")
Source("output_datapath.cc")
Source("payload_datapath.cc")
Source("pe_datapath.cc")
Source("resource_config.cc")
Source("result_scheduler.cc")
Source("schedule_state.cc")
Source("sau_model.cc")
Source("state_trace_writer.cc")
Source("systolic_array.cc")
Source("timing_policy.cc")
Source("token_pipeline.cc")
Source("trace_writer.cc")
Source("transposer.cc")

DebugFlag("SAU")

GTest("address_generator.test", "address_generator.test.cc",
      "address_generator.cc", "command.cc")
GTest("address_program.test", "address_program.test.cc",
      "address_program.cc", "resource_config.cc")
GTest("boundary_trace.test", "boundary_trace.test.cc", "boundary_trace.cc",
      "address_program.cc", "functional_memory.cc", "input_datapath.cc",
      "resource_config.cc", "transposer.cc")
GTest("a_register_file.test", "a_register_file.test.cc",
      "a_register_file.cc", "command.cc")
GTest("array_input_scheduler.test", "array_input_scheduler.test.cc",
      "array_input_scheduler.cc")
GTest("command.test", "command.test.cc", "command.cc")
GTest("csr_config.test", "csr_config.test.cc", "csr_config.cc", "command.cc",
      "resource_config.cc", "timing_policy.cc")
GTest("data_beat.test", "data_beat.test.cc")
GTest("functional_memory.test", "functional_memory.test.cc",
      "functional_memory.cc")
GTest("input_datapath.test", "input_datapath.test.cc", "input_datapath.cc")
GTest("memory_port.test", "memory_port.test.cc", "memory_port.cc",
      "../mem/packet.cc", "../mem/port.cc", "../mem/protocol/functional.cc",
      "../mem/protocol/timing.cc", "../sim/bufval.cc", "../sim/port.cc",
      with_tag("gem5 trace"))
GTest("output_datapath.test", "output_datapath.test.cc",
      "output_datapath.cc")
GTest("payload_datapath.test", "payload_datapath.test.cc",
      "payload_datapath.cc", "input_datapath.cc", "resource_config.cc",
      "systolic_array.cc", "pe_datapath.cc", "transposer.cc")
GTest("pe_datapath.test", "pe_datapath.test.cc", "pe_datapath.cc")
GTest("resource_config.test", "resource_config.test.cc",
      "resource_config.cc")
GTest("token_pipeline.test", "token_pipeline.test.cc", "token_pipeline.cc")
GTest("trace_writer.test", "trace_writer.test.cc", "trace_writer.cc")
GTest("transposer.test", "transposer.test.cc", "transposer.cc",
      "resource_config.cc")
GTest("result_scheduler.test", "result_scheduler.test.cc",
      "result_scheduler.cc")
GTest("schedule_state.test", "schedule_state.test.cc", "schedule_state.cc")
GTest("systolic_array.test", "systolic_array.test.cc",
      "systolic_array.cc", "pe_datapath.cc")
GTest("timing_policy.test", "timing_policy.test.cc", "timing_policy.cc")
